/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hospitalmanager.FrontDesk;

import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.PrintWriter;
import javax.swing.JOptionPane;

/**
 *
 * @author guest123
 */
public class AddAppointmentUI extends javax.swing.JFrame {

    /**
     * Creates new form AddAppointmentUI
     */
    public AddAppointmentUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        FirstName = new javax.swing.JTextField();
        Email = new javax.swing.JTextField();
        LastName = new javax.swing.JTextField();
        Date = new javax.swing.JComboBox<>();
        Doctor = new javax.swing.JComboBox<>();
        Month = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        Year = new javax.swing.JComboBox<>();
        Save = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        PhoneNumber = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(47, 47, 49));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("First Name");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("Last Name");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setText("Doctor");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 204, 204));
        jLabel8.setText("Email");

        FirstName.setBackground(new java.awt.Color(36, 38, 39));
        FirstName.setForeground(new java.awt.Color(204, 204, 204));
        FirstName.setText("First Name");
        FirstName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                FirstNameFocusGained(evt);
            }
        });
        FirstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FirstNameActionPerformed(evt);
            }
        });

        Email.setBackground(new java.awt.Color(36, 38, 39));
        Email.setForeground(new java.awt.Color(204, 204, 204));
        Email.setText("Email");
        Email.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                EmailFocusGained(evt);
            }
        });
        Email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmailActionPerformed(evt);
            }
        });

        LastName.setBackground(new java.awt.Color(36, 38, 39));
        LastName.setForeground(new java.awt.Color(204, 204, 204));
        LastName.setText("Last Name");
        LastName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                LastNameFocusGained(evt);
            }
        });
        LastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LastNameActionPerformed(evt);
            }
        });

        Date.setBackground(new java.awt.Color(0, 0, 0));
        Date.setForeground(new java.awt.Color(204, 204, 204));
        Date.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Dr. Handsome boizzz", "Dr. Kiarash Mirkamandari" }));
        Date.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                DateFocusGained(evt);
            }
        });
        Date.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DateActionPerformed(evt);
            }
        });

        Doctor.setBackground(new java.awt.Color(0, 0, 0));
        Doctor.setForeground(new java.awt.Color(204, 204, 204));
        Doctor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Dr. Duy Bui", "Dr. Jay Lewitsky", "Dr. Kiarash Mirkamandari", "Dr. Disen Kariyawasam " }));
        Doctor.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                DoctorFocusGained(evt);
            }
        });

        Month.setBackground(new java.awt.Color(0, 0, 0));
        Month.setForeground(new java.awt.Color(204, 204, 204));
        Month.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));
        Month.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                MonthFocusGained(evt);
            }
        });
        Month.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MonthActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(25, 25, 25));
        jButton1.setForeground(new java.awt.Color(204, 204, 204));
        jButton1.setText("Cancel");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        Year.setBackground(new java.awt.Color(0, 0, 0));
        Year.setForeground(new java.awt.Color(204, 204, 204));
        Year.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "2022", "2023", "2024", "2025" }));
        Year.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                YearFocusGained(evt);
            }
        });
        Year.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                YearActionPerformed(evt);
            }
        });

        Save.setBackground(new java.awt.Color(25, 25, 25));
        Save.setForeground(new java.awt.Color(204, 204, 204));
        Save.setText("Save");
        Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(204, 204, 204));
        jLabel11.setText("Month");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 204, 204));
        jLabel7.setText("Year");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(204, 204, 204));
        jLabel12.setText("Date");

        jPanel2.setBackground(new java.awt.Color(42, 42, 44));
        jPanel2.setForeground(new java.awt.Color(51, 51, 51));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospitalmanager/Icons/icons8_calendar_32px_1.png"))); // NOI18N
        jLabel2.setText("Request appointment");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setText("Phone Number");

        PhoneNumber.setBackground(new java.awt.Color(36, 38, 39));
        PhoneNumber.setForeground(new java.awt.Color(204, 204, 204));
        PhoneNumber.setText("Phone Number");
        PhoneNumber.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                PhoneNumberFocusGained(evt);
            }
        });
        PhoneNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PhoneNumberActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(FirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(LastName, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(PhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(Email, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(67, 67, 67)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(Doctor, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Date, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Month, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Year, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addContainerGap(44, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addComponent(Save)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(128, 128, 128))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Year, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Month, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PhoneNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Doctor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Save)
                    .addComponent(jButton1))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void FirstNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_FirstNameFocusGained
        if(FirstName.getText().equals("First Name"))FirstName.setText("");
        if(LastName.getText().length()==0)LastName.setText("Last Name");
        if(PhoneNumber.getText().length()==0) PhoneNumber.setText("Phone Number");
        if(Email.getText().length()==0) Email.setText("Email");
    }//GEN-LAST:event_FirstNameFocusGained

    private void FirstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FirstNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FirstNameActionPerformed

    private void EmailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_EmailFocusGained
        if(Email.getText().equals("Email")) Email.setText("");
        if(FirstName.getText().length()==0)FirstName.setText("First Name");
        if(LastName.getText().length()==0) LastName.setText("Last Name");
        if(PhoneNumber.getText().length()==0) PhoneNumber.setText("Phone Number");
    }//GEN-LAST:event_EmailFocusGained

    private void EmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmailActionPerformed

    private void LastNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_LastNameFocusGained
        if(LastName.getText().equals("Last Name"))LastName.setText("");
        if(FirstName.getText().length()==0)FirstName.setText("First Name");
        if(PhoneNumber.getText().length()==0) PhoneNumber.setText("Phone Number");
        if(Email.getText().length()==0) Email.setText("Email");
    }//GEN-LAST:event_LastNameFocusGained

    private void LastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LastNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LastNameActionPerformed

    private void DateFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_DateFocusGained
        if(FirstName.getText().length()==0)FirstName.setText("First Name");
        if(LastName.getText().length()==0)LastName.setText("Last Name");
        if(PhoneNumber.getText().length()==0) PhoneNumber.setText("Phone Number");
        if(Email.getText().length()==0) Email.setText("Email");

        if (Month.getSelectedItem().equals("Select"))
        {
            Date.removeAllItems();
            Date.addItem("Select");
        }
        else if (Month.getSelectedItem().equals("January") || Month.getSelectedItem().equals("March") ||
            Month.getSelectedItem().equals("May") || Month.getSelectedItem().equals("July") ||
            Month.getSelectedItem().equals("August") || Month.getSelectedItem().equals("October") ||
            Month.getSelectedItem().equals("December"))
        {
            Date.removeAllItems();
            Date.addItem("Select");
            for (int i = 1; i <= 31; i++)
            {
                Date.addItem(i + "");
            }
        }
        else if (Month.getSelectedItem().equals("February"))
        {
            Date.removeAllItems();
            Date.addItem("Select");
            if (Year.getSelectedItem().equals("2024"))
            {
                for (int i = 1; i <= 29; i++)
                {
                    Date.addItem(i + "");
                }
            }
            else
            {
                for (int i = 1; i <= 28; i++)
                {
                    Date.addItem(i + "");
                }
            }
        }
        else
        {
            Date.removeAllItems();
            Date.addItem("Select");
            for (int i = 1; i <= 30; i++)
            {
                Date.addItem(i + "");
            }

        }
    }//GEN-LAST:event_DateFocusGained

    private void DateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DateActionPerformed

    private void DoctorFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_DoctorFocusGained
        if(FirstName.getText().length()==0)FirstName.setText("First Name");
        if(LastName.getText().length()==0)LastName.setText("Last Name");
        if(PhoneNumber.getText().length()==0) PhoneNumber.setText("Phone Number");
        if(Email.getText().length()==0) Email.setText("Email");
    }//GEN-LAST:event_DoctorFocusGained

    private void MonthFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_MonthFocusGained
        if(FirstName.getText().length()==0)FirstName.setText("First Name");
        if(LastName.getText().length()==0)LastName.setText("Last Name");
        if(PhoneNumber.getText().length()==0) PhoneNumber.setText("Phone Number");
        if(Email.getText().length()==0) Email.setText("Email");

        if (Year.getSelectedItem().equals("Select"))
        {
            Month.removeAllItems();
            Month.addItem("Select");
        }
        else
        {
            Month.removeAllItems();
            Month.addItem("Select");
            Month.addItem("January");
            Month.addItem("February");
            Month.addItem("March");
            Month.addItem("April");
            Month.addItem("May");
            Month.addItem("June");
            Month.addItem("July");
            Month.addItem("August");
            Month.addItem("September");
            Month.addItem("October");
            Month.addItem("November");
            Month.addItem("December");
        }
    }//GEN-LAST:event_MonthFocusGained

    private void MonthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MonthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MonthActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void YearFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_YearFocusGained
        if(FirstName.getText().length()==0)FirstName.setText("First Name");
        if(LastName.getText().length()==0)LastName.setText("Last Name");
        if(PhoneNumber.getText().length()==0) PhoneNumber.setText("Phone Number");
        if(Email.getText().length()==0) Email.setText("Email");
    }//GEN-LAST:event_YearFocusGained

    private void YearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_YearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_YearActionPerformed

    private void SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveActionPerformed
        String filepath = "src\\hospitalmanager\\Appointments.csv";

        if (FirstName.getText().equals("First Name") || FirstName.getText().equals("") ||
            LastName.getText().equals("Last Name") || LastName.getText().equals("") ||
            Doctor.getSelectedItem().equals("Select") || Date.getSelectedItem().equals("Select") ||
            Month.getSelectedItem().equals("Select") || Year.getSelectedItem().equals("Select"))
        {
            if ((FirstName.getText().equals("First Name") || FirstName.getText().equals("") ||
                LastName.getText().equals("Last Name") || LastName.getText().equals("")) &&
            Doctor.getSelectedItem().equals("Select"))
            {
            JOptionPane.showMessageDialog(null, "Please fill all the fields and select a doctor");
            }
            else if  (Doctor.getSelectedItem().equals("Select"))
            {
                JOptionPane.showMessageDialog(null, "Please select a doctor");
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Please fill all the fields");
            }
        }
        else
        {
            try
            {
                FileWriter fw = new FileWriter(filepath, true);
                BufferedWriter bw = new BufferedWriter(fw);
                PrintWriter pw = new PrintWriter(bw);
                
                int dateValue = 0;
                
                if(Month.getSelectedItem().equals("January")) dateValue+=30;
                else if(Month.getSelectedItem().equals("February")) dateValue+=60;
                else if(Month.getSelectedItem().equals("March")) dateValue+=90;
                else if(Month.getSelectedItem().equals("April")) dateValue+=120;
                else if(Month.getSelectedItem().equals("May")) dateValue+=150;
                else if(Month.getSelectedItem().equals("June")) dateValue+=180;
                else if(Month.getSelectedItem().equals("July")) dateValue+=210;
                else if(Month.getSelectedItem().equals("August")) dateValue+=240;
                else if(Month.getSelectedItem().equals("September")) dateValue+=270;
                else if(Month.getSelectedItem().equals("October")) dateValue+=300;
                else if(Month.getSelectedItem().equals("November")) dateValue+=330;
                else if(Month.getSelectedItem().equals("December")) dateValue+=360;
                    
                dateValue+=Date.getSelectedIndex();
                
                dateValue+=(Year.getSelectedIndex()+1)*1000;
                    
                int docIndex = Doctor.getSelectedIndex();
                
                
                pw.println(dateValue+","+FirstName.getText()+","+LastName.getText()+","+PhoneNumber.getText()+","+Email.getText()+","+
                    docIndex+","+Date.getSelectedItem()+","+Month.getSelectedItem()+","+Year.getSelectedItem());
                pw.flush();
                pw.close();

                JOptionPane.showMessageDialog(null, "Appointment Added");

            }
            catch(Exception e)
            {

            }

        }

    }//GEN-LAST:event_SaveActionPerformed

    private void PhoneNumberFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PhoneNumberFocusGained
        if(PhoneNumber.getText().equals("Phone Number")) PhoneNumber.setText("");
        if(FirstName.getText().length()==0)FirstName.setText("First Name");
        if(LastName.getText().length()==0) LastName.setText("Last Name");
        if(Email.getText().length()==0) Email.setText("Email");
    }//GEN-LAST:event_PhoneNumberFocusGained

    private void PhoneNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PhoneNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PhoneNumberActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddAppointmentUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddAppointmentUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddAppointmentUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddAppointmentUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddAppointmentUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Date;
    private javax.swing.JComboBox<String> Doctor;
    private javax.swing.JTextField Email;
    private javax.swing.JTextField FirstName;
    private javax.swing.JTextField LastName;
    private javax.swing.JComboBox<String> Month;
    private javax.swing.JTextField PhoneNumber;
    private javax.swing.JButton Save;
    public javax.swing.JComboBox<String> Year;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
